# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dispatch < Formula
  desc "A CLI utility for deploying kOps Kubernetes in AWS"
  homepage "https://github.com/christianTragesser/dispatch"
  version "0.1.7"
  license "MIT"

  on_macos do
    url "https://github.com/christianTragesser/dispatch/releases/download/v0.1.7/dispatch_0.1.7_darwin_amd64.tar.gz"
    sha256 "2fdb3638c09e2d5ad8f9d68cbf3690a28b07d303be48ca010a5b7f927b325868"

    def install
      bin.install "dispatch-darwin-amd64"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Dispatch
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/christianTragesser/dispatch/releases/download/v0.1.7/dispatch_0.1.7_linux_amd64.tar.gz"
      sha256 "eca72cf09c0c9d76467da1383a773da74ab517b33f51663613018dcef08f34b2"

      def install
        bin.install "dispatch-linux-amd64"
      end
    end
  end

  def post_install
    system "rm -f /usr/local/bin/dispatch || true"
    system "ln -s #{bin}/dispatch-* /usr/local/bin/dispatch"
  end

  test do
    system "#{bin}/dispatch version"
  end
end
