# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dispatch < Formula
  desc "A CLI utility for deploying KOPS Kubernetes in AWS"
  homepage "https://github.com/christianTragesser/dispatch"
  version "0.1.2"
  license "MIT"

  on_macos do
    url "https://github.com/christianTragesser/dispatch/releases/download/v0.1.2/dispatch_0.1.2_darwin_amd64.tar.gz"
    sha256 "c772d6e2a4897caad0b3b911e08298aff5cdce4b067eb8f65a9848afb7225014"

    def install
      bin.install "dispatch-darwin-amd64"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Dispatch
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/christianTragesser/dispatch/releases/download/v0.1.2/dispatch_0.1.2_linux_amd64.tar.gz"
      sha256 "f04e9268a563405b025575e6a5491c9ea08070dd754a763cab378bbc04a64f12"

      def install
        bin.install "dispatch-linux-amd64"
      end
    end
  end

  def post_install
    system "rm -f /usr/local/bin/dispatch || true"
    system "ln -s #{bin}/dispatch-* /usr/local/bin/dispatch"
  end

  test do
    system "#{bin}/dispatch version"
  end
end
