# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnsexit < Formula
  desc "A DNSExit dynamic ip address DNS client"
  homepage "https://github.com/christianTragesser/dnsexit-ip-update"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/christianTragesser/dnsexit-ip-update/releases/download/v0.3.0/dnsexit_0.3.0_darwin_amd64.tar.gz"
      sha256 "c17d20a55788bf539ff682eaf2784d58714a20bfbe1257884c63a0725d466bb5"

      def install
        bin.install "dnsexit-darwin-amd64"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/christianTragesser/dnsexit-ip-update/releases/download/v0.3.0/dnsexit_0.3.0_darwin_arm64.tar.gz"
      sha256 "cfb7bc6b16bf8f7c47d24bf536669a29fbb6209e529e3ea7a814376186fac150"

      def install
        bin.install "dnsexit-darwin-arm64"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/christianTragesser/dnsexit-ip-update/releases/download/v0.3.0/dnsexit_0.3.0_linux_amd64.tar.gz"
      sha256 "0498734ce5f6859bb0344dd23add4d32d203b2f28d2301f6e818c926be776437"

      def install
        bin.install "dnsexit-linux-amd64"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/christianTragesser/dnsexit-ip-update/releases/download/v0.3.0/dnsexit_0.3.0_linux_arm64.tar.gz"
      sha256 "b31c994e18540b06e99938d1e7eaa7c6c9060f25d470b7964cdf4af90bc214dc"

      def install
        bin.install "dnsexit-linux-arm64"
      end
    end
  end

  def post_install
    system "rm -f /usr/local/bin/dnsexit || true"
    system "ln -s #{bin}/dnsexit-* /usr/local/bin/dnsexit"
  end

  test do
    system "/usr/local/bin/dnsexit version"
  end
end
